### ISSUE TITLE
Create TopVisitedPagesTable

### ISSUE THREAD

**Issue by suvasan19** [harled/matey#10]
![image](https://user-images.githubusercontent.com/55468742/159372038-1e366331-d1b1-4a22-ab1d-ae023470e7b6.png)

Currently open to discussion on what kinds of tech to use for the table. Styling is also up for debate.

**Comment by jonathanloos** [comment]
@suvasan19 think this is almost good to go!
<img width="685" alt="Screen Shot 2022-03-26 at 12 38 15 AM" src="https://user-images.githubusercontent.com/16821802/160224880-51d97844-9a05-40a2-a964-165aa987ea86.png">

**Comment by suvasan19** [comment]
Looks Great 🔥 🔥 🔥 !!! Awesome work!
