### ISSUE TITLE
Create TopEventsComponent

### ISSUE THREAD

**Issue by suvasan19** [harled/matey#11]
![image](https://user-images.githubusercontent.com/55468742/159372182-4b1757d7-cc92-4f2a-a4d6-83c231576c96.png)

View Component for top events that are tracked using Ahoy. Show each event as well as the amount of times it has happened in the given period. Styling and tech used are up for discussion

**Comment by krsyoung** [comment]
Not exactly pretty ...

<img width="351" alt="image" src="https://user-images.githubusercontent.com/5449541/161188670-9aa1ba99-c5c1-4f21-93c6-b75f02c648d7.png">

**Comment by suvasan19** [comment]
Definitely a good start! Could we add a total count like @jonathanloos added with his table. Styling should help out with this too!

![image](https://user-images.githubusercontent.com/55468742/161198875-f6969944-9932-485d-8c9f-e26b2917c7e2.png)
