### ISSUE TITLE
Custom Card Component

### ISSUE THREAD

**Issue by suvasan19** [harled/matey#28]
Create custom card component that mimics other card components.Should have:
- custom title
- time_window
- data

**Comment by krsyoung** [comment]
@caitmich thoughts on triaging for now (at least until we hit this in one of our apps)? I'm not exactly clear on how this would work in terms of the actual calculation?

**Comment by caitmich** [comment]
@krsyoung Agree here too, for now

**Comment by suvasan19** [comment]
Would just be a way for users to add their own data in. I was thinking it would mimic the other components but allows the number and title to be inputted
