### ISSUE TITLE
Custom Table Component

### ISSUE THREAD

**Issue by suvasan19** [harled/matey#29]

**Comment by krsyoung** [comment]
@caitmich thoughts on triaging for now (at least until we hit this in one of our apps)? I'm not exactly clear on how this would work in terms of the actual calculation?

**Comment by caitmich** [comment]
@krsyoung yeah I'm fine with that- this would give a user the ability to create a custom component?

**Comment by krsyoung** [comment]
Not sure, @suvasan19 can remind us when his ✈️ lands??

**Comment by suvasan19** [comment]
Similar to Custom Card Component. Allow users to enter a hash with any keys and numerical values that would be displayed in a table

**Comment by krsyoung** [comment]
Thanks @suvasan19. p.s. we miss you!
