### ISSUE TITLE
Create NewUsersComponent

### ISSUE THREAD

**Issue by suvasan19** [harled/matey#3]
The next component will be an NewUsersComponent. This component will:

Report on the new users over time
Report the change from the previous period
Render a card including the new users, absolute change from last period and the % change from last period

![image](https://user-images.githubusercontent.com/55468742/158479107-1b64d2c9-31eb-48c6-9082-691ac3fa0d7f.png)

**Comment by krsyoung** [comment]
@suvasan19 happy to take this but will wait for #2 to merge before starting work.

**Comment by krsyoung** [comment]
Not pretty, but it is a start @suvasan19. Thoughts on you creating a "pretty" version that we can reference?

<img width="257" alt="image" src="https://user-images.githubusercontent.com/5449541/159607816-03a6c90f-613c-4201-957a-faca386f2727.png">

**Comment by suvasan19** [comment]
Ya that's a good idea. So making a different component but just adding styling

**Comment by krsyoung** [comment]
Yeah, could even just style this one correctly? It is "close" but definitely wouldn't want to copy & paste it too many times (need to float the text to the bottom of the card, figure out the font sizes etc..).

I'm thinking down the road we'll also need to allow individuals to added classes. Probably early to fix it, but something we should consider.

**Comment by suvasan19** [comment]
![image](https://user-images.githubusercontent.com/55468742/159847812-2db424c0-3cb5-4296-b7d2-1f04379dc30a.png)

Added some basic styling for right now, should style all components that follow the same structure
