### ISSUE TITLE
Create a DAU Component

### ISSUE THREAD

**Issue by krsyoung** [harled/matey#44]
Create a component that tracks the average number of daily active users (DAU) which is a common user engagement metric.

Key features would include:
* standard DAU average over the past 30 days
* based on a visit within a 24 hour period

Possible extensions would include:
* customize the average range via a parameter (number of days)
* parameter to indicate weekly or monthly periods
* allow the user to select the window range via a dropdown in the component
* display a graph that trends the DAU over the window period of time

Might be helpful: 
* https://stackoverflow.com/questions/59001535/whats-the-most-efficient-way-to-calculate-daily-active-users-leveraging-the-rai

**Comment by krsyoung** [comment]
@ddnguyen93 is this being actively worked on?

**Comment by alexmcdermid** [comment]
Started some work on this.

https://github.com/harled/matey/pull/70
