### ISSUE TITLE
Bounce Rate

### ISSUE THREAD

**Issue by jonathanloos** [harled/matey#45]
The bounce rate indicates the number of users who hit one page then leave your site.
User **visits** a SINGLE page -> User leaves website

Bounce rate is calculated by **the total number of one-page visits divided by the total number of entries to a website**.

Benefits:

- It identifies whether or not users are finding the landing page to this app useful/engaging/compelling
- For large scale applications it can identify bookmarked pages (i.e. pages that were checked once then left).
- Pages with high bounce rates may be an indicator of bad formatting, poor solution, or long loadtimes.

_Note: High Bounce Rate isn't always bad, if the success of your site depends on users viewing more than one page, then a high bounce rate is bad. But, if your site's success depends on users immediately finding what they were looking on a particular page, then a high bounce rate would be ideal._

**Comment by pJeyakumar** [comment]
**Boom!** Here's the widget! It shows your application's bounce rate, the total number of bounced page visits, the total number of visits, & a table showing the top 5 most bounced pages and their bounce count! 
<img width="339" alt="Screen Shot 2022-08-14 at 1 13 33 PM" src="https://user-images.githubusercontent.com/57971751/184547735-3d6f8e10-c646-4f66-a6b8-cb534664cb78.png">
