### ISSUE TITLE
Initializer for default background color and text color

### ISSUE THREAD

**Issue by krsyoung** [harled/matey#65]
The components are currently opinionated in that they use a `bg-primary` and a `text-light` for the cards.

In some UIs this can be a little .. uhh .. offensive! It would be nice to have the default be very neutral, however, still over the option to customize the background and text colours for all cards.

In the future, it might make sense to add the options as overrides on a per component basis.

**Comment by johnmal-dev** [comment]
I'd love to jump in on this one
