### ISSUE TITLE
Upgrade View Components Dependency to 3.9.0

### ISSUE THREAD

**Issue by jonathanloos** [harled/matey#89]
There is an available view component security update released here: https://github.com/ViewComponent/view_component/security/advisories/GHSA-wf2x-8w6j-qw37. 

Current version in Matey: `2.74`
Target version update: `3.9.0`

**Comment by krsyoung** [comment]
Thinking this should be released as 0.2.0 (should be a major version but we didn't seem to hit 1.0.0 yet).
